name = "osaka"
description = "Omarchy Osaka Jade theme palette"

[colors]
background = "#111c18"
darker_background = "#090f0d"
lighter_background = "#23372B"
foreground = "#C1C497"
bright_foreground = "#F7E8B2"
muted = "#53685B"
accent = "#509475"
primary = "#509475"
secondary = "#2DD5B7"
red = "#FF5345"
green = "#549e6a"
yellow = "#459451"
blue = "#509475"
magenta = "#D2689C"
cyan = "#2DD5B7"
orange = "#a2734b"
